"""Pluggable submission channels for SUBMISSION_AGENT.

The previous SUBMISSION_AGENT built packages but didn't actually transmit
them anywhere. This module introduces a channel abstraction so we can
wire real payer portals as they become available without rewriting the
pipeline.

Today's channels:

  - MockChannel — returns a realistic confirmation number. Used for demos
    and the initial pilot where no real payer credentials exist yet. Every
    submission is persisted and tracked end-to-end.

  - FaxChannel — generates a formatted cover sheet PDF, marks the
    submission as "fax_queued", and hands off to a human/queue for
    dispatch. Many smaller payers still require fax.

  - PortalChannel — scaffolding for real portal integration (UHC Availity,
    Aetna eviCore). Returns a "pending_credentials" state today. When
    trading-partner agreements + credentials are in place, each adapter
    implements .submit() against the portal's API/automation.

Adding a new payer: subclass SubmissionChannel, implement .submit(), and
register it in CHANNEL_REGISTRY below.
"""

from __future__ import annotations

import logging
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Literal

logger = logging.getLogger(__name__)


ChannelStatus = Literal[
    "submitted",            # Transmitted + confirmed
    "fax_queued",           # Printed/generated, awaiting human dispatch
    "pending_credentials",  # Adapter exists but credentials not configured
    "failed",               # Transmission failed
]


@dataclass
class SubmissionPackage:
    """What goes TO a channel."""
    submission_id: str
    patient_id: str
    payer: str
    procedure_name: str
    cpt_code: str
    cover_summary: str
    pdf_bytes: bytes
    metadata: dict = field(default_factory=dict)


@dataclass
class ChannelResult:
    """What comes back FROM a channel."""
    status: ChannelStatus
    confirmation_number: str = ""
    expected_decision_date: str = ""
    submitted_at: str = ""
    channel_notes: str = ""
    requires_human_action: str = ""


# ────────────────────────────────────────────────────────────────────────
# Channel interface
# ────────────────────────────────────────────────────────────────────────


class SubmissionChannel(ABC):
    """Base class for every submission channel."""

    name: str = "abstract"

    @abstractmethod
    def submit(self, package: SubmissionPackage) -> ChannelResult: ...

    def _now_iso(self) -> str:
        return datetime.now(timezone.utc).isoformat()


# ────────────────────────────────────────────────────────────────────────
# Mock channel — production-safe fallback, used for demos + pilot
# ────────────────────────────────────────────────────────────────────────


class MockChannel(SubmissionChannel):
    """A mock that behaves like a real channel. Used until real payer
    integrations are wired. Produces a deterministic confirmation number
    and a reasonable expected-decision date.
    """

    name = "mock"

    def submit(self, package: SubmissionPackage) -> ChannelResult:
        confirmation = f"MOCK-{package.submission_id[-6:].upper()}-{uuid.uuid4().hex[:4].upper()}"
        # Simulate a 5-business-day turnaround
        from datetime import timedelta
        expected = datetime.now(timezone.utc) + timedelta(days=5)
        logger.info(
            "MockChannel submitted %s (payer=%s, CPT=%s) → confirmation=%s",
            package.submission_id, package.payer, package.cpt_code, confirmation,
        )
        return ChannelResult(
            status="submitted",
            confirmation_number=confirmation,
            expected_decision_date=expected.date().isoformat(),
            submitted_at=self._now_iso(),
            channel_notes="MockChannel — no real payer transmission. Use for testing / pilot.",
        )


# ────────────────────────────────────────────────────────────────────────
# Fax channel — still required by many payers
# ────────────────────────────────────────────────────────────────────────


class FaxChannel(SubmissionChannel):
    """Queues a submission for fax dispatch. PDF already generated by
    SUBMISSION_AGENT; here we mark it ready for a human to fax and
    capture the cover-sheet metadata.
    """

    name = "fax"

    def submit(self, package: SubmissionPackage) -> ChannelResult:
        queue_id = f"FAX-Q-{uuid.uuid4().hex[:8].upper()}"
        logger.info(
            "FaxChannel queued %s for dispatch (payer=%s, CPT=%s) → queue_id=%s (PDF size=%d bytes)",
            package.submission_id, package.payer, package.cpt_code, queue_id, len(package.pdf_bytes),
        )
        return ChannelResult(
            status="fax_queued",
            confirmation_number=queue_id,
            submitted_at=self._now_iso(),
            channel_notes=(
                "Submission is staged for fax dispatch. A back-office staff member "
                "must fax the attached PDF to the payer's documented PA fax number. "
                "Record the confirmation sheet as proof of transmission."
            ),
            requires_human_action=(
                f"Fax the submission packet for {package.submission_id} to {package.payer}'s "
                "prior-auth fax number. Retain the transmission receipt."
            ),
        )


# ────────────────────────────────────────────────────────────────────────
# Portal channel — scaffolding for real payer portals
# ────────────────────────────────────────────────────────────────────────


class PortalChannel(SubmissionChannel):
    """Scaffolding for real payer portals (Availity, eviCore, UHC Provider).

    Today returns pending_credentials — a real adapter needs:
      1. Trading-partner agreement with the payer / clearinghouse
      2. API credentials or RPA automation for portal navigation
      3. Per-payer field mapping from CardioAuth schema → payer form

    When a real adapter lands, subclass this (e.g. AvailityChannel) and
    override .submit() with the actual API / automation call.
    """

    name = "portal"
    supported_payers: list[str] = []  # Override in subclass

    def __init__(self, payer: str) -> None:
        self.payer = payer

    def submit(self, package: SubmissionPackage) -> ChannelResult:
        logger.warning(
            "PortalChannel (generic) invoked for %s — credentials not configured",
            self.payer,
        )
        return ChannelResult(
            status="pending_credentials",
            submitted_at=self._now_iso(),
            channel_notes=(
                f"Portal adapter for {self.payer} is scaffolded but not live. "
                "Requires trading-partner agreement + portal credentials. "
                "Use MockChannel or FaxChannel in the interim."
            ),
            requires_human_action=(
                f"Manually submit the packet to {self.payer}'s provider portal and "
                "record the confirmation number via POST /api/pa/submission/:id/record-confirmation."
            ),
        )


class AvailityChannel(PortalChannel):
    """Availity clearinghouse adapter (UnitedHealthcare, several Blues plans).

    Status: scaffolding. Real implementation requires Availity B2B
    credentials + EDI 278 trading-partner agreement.
    """

    name = "availity"
    supported_payers = ["UnitedHealthcare", "BCBS"]


class EviCoreChannel(PortalChannel):
    """eviCore adapter (Aetna advanced imaging + several other payers).

    Status: scaffolding. Real implementation requires eviCore portal
    credentials + Aetna routing agreement.
    """

    name = "evicore"
    supported_payers = ["Aetna"]


# ────────────────────────────────────────────────────────────────────────
# Registry + routing
# ────────────────────────────────────────────────────────────────────────


def get_channel_for(payer: str, submission_format: str = "") -> SubmissionChannel:
    """Pick the right channel based on payer + requested format.

    Order:
      1. If format explicitly says fax, FaxChannel.
      2. If the payer has a registered portal adapter, use it.
      3. Default to MockChannel (safe — doesn't actually transmit to a
         real payer, so no risk of misfiled cases during development).
    """
    fmt = (submission_format or "").lower()
    if fmt == "fax":
        return FaxChannel()

    payer_lower = (payer or "").lower()

    # Availity handles UHC + BCBS
    if payer_lower in ("unitedhealthcare", "uhc", "united"):
        return AvailityChannel(payer=payer)
    if "blue" in payer_lower or payer_lower.startswith("bcbs"):
        return AvailityChannel(payer=payer)

    # eviCore for Aetna advanced imaging
    if payer_lower in ("aetna",):
        return EviCoreChannel(payer=payer)

    # Default: Mock. Safer than silently submitting somewhere wrong.
    return MockChannel()
